services:
  app:
    build:
      context: .
    ports:
      - "8787:8787"
    volumes:
      - "/app/node_modules"
      - "./:/app"
      - "./.wrangler/config/default.toml:/root/.wrangler/config/default.toml:ro"
    command: "npm run dev"
    env_file:
      - ".env"