name = "commit-reminder"
type = "javascript"
zone_id = ""
account_id = "1146b5f051ea47c3cbd0da1e64394984"
route = ""
workers_dev = true
compatibility_date = "2022-04-29"
kv_namespaces = [
   { binding = "CR_KV", id = "5742ed807c6d46bb825bec92f1c2ef96" }
]

# [secrets]
# GITHUB_TOKEN
# SLACK_BOT_TOKEN
# SLACK_SIGNING_SECRET
# SLACK_WEBHOOK_URL
# SLACK_USER_ID
# SECRET_PATH

[variables]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
