name = "commit-reminder"
type = "javascript"
zone_id = ""
account_id = "1146b5f051ea47c3cbd0da1e64394984"
route = ""
workers_dev = true
compatibility_date = "2022-04-29"

# [secrets]
# GITHUB_TOKEN
# SLACK_BOT_TOKEN
# SLACK_SIGNING_SECRET
# SLACK_WEBHOOK_URL
# SLACK_USER_ID
# SECRET_PATH

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
