/* eslint-disable no-var */
declare var GITHUB_TOKEN: string
declare var GITHUB_TOKEN: string
declare var SLACK_BOT_TOKEN: string
declare var SLACK_SIGNING_SECRET: string
declare var SLACK_WEBHOOK_URL: string
declare var SLACK_USER_ID: string
declare var SECRET_PATH: string
/* eslint-enable no-var */
